### ISSUE TITLE
the problem in model.py

### ISSUE THREAD

**Issue by LearnerHong** [medtray/DAME#3]
I found a problem in your code, but I'm not sure my conclusion is correct. I hope I can get your reply
the code in line 453, 507 and 575
```python
logits = self.task_classifier(o)
```
I think it should be modified as follows, otherwise the operation fails
```python
feat=torch.cat([o,shared_output],dim=1)
logits = self.task_classifier(feat)
```

**Comment by medtray** [comment]
Thank you for your feedback. If I remember correctly, I think I was trying to study the effect of the expert models without the intervention of the global model as additional feature (only used for attention weights computations), therefore I believe I had different dimension for line 310 (multi_xformer.d_model instead of 2*multi_xformer.d_model). But as a final model, it should be changed the way you mentioned.
